# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "dependencies"
      - "go"
      - "type::security"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    groups:
      security:
        update-types:
          - "patch"
          - "minor"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
      - "type::security"
    schedule:
      interval: "weekly"
